### ISSUE TITLE
Samsung Dex mod compiled 

### ISSUE THREAD

**Issue by WilsonBradley** [supermarsx/magisk-samsung-dex-standalone-mode#1]
Magisk, haven't heard that in years, this only works on rooted android devices?
Is there a compiled version somewhere? 

Thanks

**Comment by supermarsx** [comment]
Hi Wilson,

this only works on rooted devices, you should have either `kernelsu` or `magisk` for it to work.
You should check "How to root (insert your phone here)" or "How to install magisk on (insert phone here)" and then you can just download the zip and install directly.
So you need to find out:
- how to root
- how to install magisk or kernelsu 
- download this module 
- install it using your chosen app.

Important notice, rooting your phone might brick it or result in other types issues.
This reply is purely informational, there are no warranties explicit or implied.
If you mess up your phone while doing so you're on your own.

This question is not related to the module in itself so i'm closing this issue.

Have a great weekend
