### ISSUE TITLE
Hi, after closing dex, the gesture mode of the "taskbar" of normal android doesn't work

### ISSUE THREAD

**Issue by Gustavoppw** [supermarsx/magisk-samsung-dex-standalone-mode#2]
I can't go back using the gestures, can you guys try to fix it? I am not saying that the module is bad, it's great

**Comment by supermarsx** [comment]
Hi Gustavo,

as a note it's just me a random regular mortal, the owner of the repository. It's a bummer you're having trouble. I'm trying to understand what do you mean by the gesture mode not working after exiting dex..

i'm suspecting you're talking about these things i found out from a google search, (reference links):

https://www.reddit.com/r/SamsungDex/comments/104t2xg/swipe_navigation_gesture_stopped_working_in/
https://www.reddit.com/r/SamsungDex/comments/s5f8g5/gesture_navigation_stops_working_after_exiting_dex/
https://www.reddit.com/r/SamsungDex/comments/16ag9z2/my_navigation_bar_doesnt_work_after_leaving_dex/

maybe try looking into these things people reference:

![image](https://github.com/user-attachments/assets/8cc223a1-20d7-415f-b3f5-c6418552d166)

![image](https://github.com/user-attachments/assets/64984a74-bc7c-4417-bb4c-f3c4d3419b5e)

![image](https://github.com/user-attachments/assets/a198451a-b147-47be-89ee-0f382242ab23)


from what i gather it's a software bug and not exactly related to the module itself..

I'm closing this issue as it's not within the scope of the module although it might be related to the fact of this hacky method of getting dex to work messes with the screen density and maybe the system doesn't handle it correctly on exiting.

If you find a different solution on your own you can comment it to let people know if the run into this issue like you.

Sorry for not having an alternative, i hope you understand, have a good week. 😊
